### ISSUE TITLE
Failed to build on FreeBSD 11.0

### ISSUE THREAD

**Issue by drpnd** [drpnd/fexporter#1]
Build failed on FreeBSD 11.0-RELEASE-p9 with FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0) and CMake 3.8.2.

```
% make
Scanning dependencies of target fexporterd
[ 20%] Building C object CMakeFiles/fexporterd.dir/fexporterd.c.o
In file included from /home/panda/src/fexporter/fexporterd.c:30:
In file included from /usr/include/netinet/if_ether.h:37:
/usr/include/net/if_arp.h:89:18: error: field has incomplete type 'struct sockaddr'
        struct  sockaddr arp_pa;                /* protocol address */
                         ^
/usr/include/pcap/pcap.h:229:9: note: forward declaration of 'struct sockaddr'
        struct sockaddr *addr;          /* address */
               ^
In file included from /home/panda/src/fexporter/fexporterd.c:30:
In file included from /usr/include/netinet/if_ether.h:37:
/usr/include/net/if_arp.h:90:18: error: field has incomplete type 'struct sockaddr'
        struct  sockaddr arp_ha;                /* hardware address */
                         ^
/usr/include/pcap/pcap.h:229:9: note: forward declaration of 'struct sockaddr'
        struct sockaddr *addr;          /* address */
               ^
In file included from /home/panda/src/fexporter/fexporterd.c:30:
/usr/include/netinet/if_ether.h:97:17: error: field has incomplete type 'struct in_addr'
        struct  in_addr sin_addr;
                        ^
/usr/include/netinet/if_ether.h:97:9: note: forward declaration of 'struct in_addr'
        struct  in_addr sin_addr;
                ^
/usr/include/netinet/if_ether.h:98:17: error: field has incomplete type 'struct in_addr'
        struct  in_addr sin_srcaddr;
                        ^
/usr/include/netinet/if_ether.h:97:9: note: forward declaration of 'struct in_addr'
        struct  in_addr sin_addr;
                ^
In file included from /home/panda/src/fexporter/fexporterd.c:31:
/usr/include/netinet/ip.h:69:17: error: field has incomplete type 'struct in_addr'
        struct  in_addr ip_src,ip_dst;  /* source and dest address */
                        ^
/usr/include/netinet/if_ether.h:97:9: note: forward declaration of 'struct in_addr'
        struct  in_addr sin_addr;
                ^
In file included from /home/panda/src/fexporter/fexporterd.c:31:
/usr/include/netinet/ip.h:69:24: error: field has incomplete type 'struct in_addr'
        struct  in_addr ip_src,ip_dst;  /* source and dest address */
                               ^
/usr/include/netinet/if_ether.h:97:9: note: forward declaration of 'struct in_addr'
        struct  in_addr sin_addr;
                ^
In file included from /home/panda/src/fexporter/fexporterd.c:31:
/usr/include/netinet/ip.h:181:19: error: field has incomplete type 'struct in_addr'
                        struct in_addr ipt_addr;
                                       ^
/usr/include/netinet/if_ether.h:97:9: note: forward declaration of 'struct in_addr'
        struct  in_addr sin_addr;
                ^
In file included from /home/panda/src/fexporter/fexporterd.c:31:
/usr/include/netinet/ip.h:216:17: error: field has incomplete type 'struct in_addr'
        struct  in_addr ippseudo_src;   /* source internet address */
                        ^
/usr/include/netinet/if_ether.h:97:9: note: forward declaration of 'struct in_addr'
        struct  in_addr sin_addr;
                ^
In file included from /home/panda/src/fexporter/fexporterd.c:31:
/usr/include/netinet/ip.h:217:17: error: field has incomplete type 'struct in_addr'
        struct  in_addr ippseudo_dst;   /* destination internet address */
                        ^
/usr/include/netinet/if_ether.h:97:9: note: forward declaration of 'struct in_addr'
        struct  in_addr sin_addr;
                ^
In file included from /home/panda/src/fexporter/fexporterd.c:32:
/usr/include/netinet/ip6.h:82:18: error: field has incomplete type 'struct in6_addr'
        struct in6_addr ip6_src;        /* source address */
                        ^
/usr/include/netinet/ip6.h:82:9: note: forward declaration of 'struct in6_addr'
        struct in6_addr ip6_src;        /* source address */
               ^
/usr/include/netinet/ip6.h:83:18: error: field has incomplete type 'struct in6_addr'
        struct in6_addr ip6_dst;        /* destination address */
                        ^
/usr/include/netinet/ip6.h:82:9: note: forward declaration of 'struct in6_addr'
        struct in6_addr ip6_src;        /* source address */
               ^
In file included from /home/panda/src/fexporter/fexporterd.c:35:
/usr/include/netinet/ip_icmp.h:69:18: error: field has incomplete type 'struct in_addr'
                struct in_addr ih_gwaddr;       /* ICMP_REDIRECT */
                               ^
/usr/include/netinet/if_ether.h:97:9: note: forward declaration of 'struct in_addr'
        struct  in_addr sin_addr;
                ^
In file included from /home/panda/src/fexporter/fexporterd.c:36:
/usr/include/netinet/icmp6.h:181:19: error: field has incomplete type 'struct in6_addr'
        struct in6_addr         mld_addr; /* multicast address */
                                ^
/usr/include/netinet/ip6.h:82:9: note: forward declaration of 'struct in6_addr'
        struct in6_addr ip6_src;        /* source address */
               ^
In file included from /home/panda/src/fexporter/fexporterd.c:36:
/usr/include/netinet/icmp6.h:249:19: error: field has incomplete type 'struct in6_addr'
        struct in6_addr         nd_ns_target;   /*target address */
                                ^
/usr/include/netinet/ip6.h:82:9: note: forward declaration of 'struct in6_addr'
        struct in6_addr ip6_src;        /* source address */
               ^
In file included from /home/panda/src/fexporter/fexporterd.c:36:
/usr/include/netinet/icmp6.h:260:19: error: field has incomplete type 'struct in6_addr'
        struct in6_addr         nd_na_target;   /* target address */
                                ^
/usr/include/netinet/ip6.h:82:9: note: forward declaration of 'struct in6_addr'
        struct in6_addr ip6_src;        /* source address */
               ^
In file included from /home/panda/src/fexporter/fexporterd.c:36:
/usr/include/netinet/icmp6.h:282:19: error: field has incomplete type 'struct in6_addr'
        struct in6_addr         nd_rd_target;   /* target address */
                                ^
/usr/include/netinet/ip6.h:82:9: note: forward declaration of 'struct in6_addr'
/usr/include/netinet/ip6.h:82:9: note: forward declaration of 'struct in6_addr'
        struct in6_addr ip6_src;        /* source address */
               ^
In file included from /home/panda/src/fexporter/fexporterd.c:36:
/usr/include/netinet/icmp6.h:317:18: error: field has incomplete type 'struct in6_addr'
        struct in6_addr nd_opt_pi_prefix;
                        ^
/usr/include/netinet/ip6.h:82:9: note: forward declaration of 'struct in6_addr'
        struct in6_addr ip6_src;        /* source address */
               ^
In file included from /home/panda/src/fexporter/fexporterd.c:36:
/usr/include/netinet/icmp6.h:490:18: error: field has incomplete type 'struct in6_addr'
        struct  in6_addr        rpm_prefix;
                                ^
/usr/include/netinet/ip6.h:82:9: note: forward declaration of 'struct in6_addr'
        struct in6_addr ip6_src;        /* source address */
               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
*** Error code 1

Stop.
make[2]: stopped in /usr/home/panda/src/fexporter
*** Error code 1

Stop.
make[1]: stopped in /usr/home/panda/src/fexporter
*** Error code 1

Stop.
make: stopped in /usr/home/panda/src/fexporter
```
